madefood/madefood/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('makefood/',include('polls.urls',namespace ='makefood'))
]

madefood/polls/urls.py
from django.urls import path

from . import views

app_name = "makefood"

urlpatterns = [
    path('recipes/',views.polls_list,name="recipes"),
	path('detail/<int:recipes_id>/',views.recipes_detail,name='detail'),
	path('detail/<int:recipes_id>/vote/',views.recipes_vote,name='vote')
]

madefood/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('makefood/',include('polls.urls',namespace ='makefood')),
    path('accounts/',include('accounts.urls',namespace ='accounts')),
    # path('accounts/',include('django.contrib.auth.urls')),
    path('aboutus/',include('aboutus.urls',namespace ='aboutus')),
]

madefood/polls/models.py
from django.db import models

# Create your models here.
class Poll(models.Model):
    text = models.CharField(max_length=255)
    description = models.CharField(max_length=5000,default='Przepis')
    pub_date = models.DateField()

    def __str__(self):
        return self.text


class Comment(models.Model):
	comment = models.ForeignKey(Poll,on_delete=models.CASCADE)
	comment_text = models.CharField(max_length = 400)
	votes = models.IntegerField(default = 0)

	def __str__(self):
		return "{} - {}".format(self.comment.text[:30],self.comment_text[:30])

madefood/madefood/views.py
from django.http import HttpResponse
from django.shortcuts import render
import datetime

def current_datetime(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html)

def home(request):
    now = datetime.datetime.now()
    context = {'datetime_now':now}
    return render(request,'home.html',context)
    #return HttpResponse('Home page ')

madefood/polls/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse
from .models import Poll,Comment
# Create your views here.
def polls_list(request):
	recipes = Poll.objects.all()
	context = {'recipes': recipes}
	return render(request,'polls/recipes.html', context)

def recipes_detail(request,recipes_id):
	# return HttpResponse('Youre looking for recipe id:{}'.format(recipes_id))
	
	# recipes = Poll.objects.get(id=recipes_id)
	recipes = get_object_or_404(Poll, id=recipes_id)

	if request.method == "POST":
		print(request.POST)
		print("You Posted!!!!")

	if request.method == "GET":
		print(request.GET)
		print("You Get Me")

	context = {'recipes': recipes}
	return render(request,'polls/recipes_detail.html',context)


def recipes_vote(request,recipes_id):
	comment_id = request.POST['comment']
	comment = Comment.objects.get(id=comment_id)
	comment.votes += 1
	comment.save()
	return HttpResponse('Recipe Id: {}'.format(recipes_id))

madefood/views.py
from django.http import HttpResponse
from django.shortcuts import render
import datetime

def home(request):
   
    return render(request,'home.html',{})
    #return HttpResponse('Home page ')

madefood/polls/templates/polls/recipes.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Welcome to recipes list</h1>
    <ul>
    {% for recipe in recipes %}
    	<li><a href="{% url 'makefood:detail' recipe.id %}">{{recipe}}</a></li>
    	{% endfor %}
	</ul>
</div>
{% endblock %}

madefood/polls/templates/polls/recipes_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Recipe Detail</h1>
{{recipes}}

<form action="{% url 'makefood:vote' recipes.id %}" method="post">
	{% csrf_token %}

	{% for comment in recipes.comment_set.all %}

	<input  type="radio" 
			name="comment"
			id = "comment{{ forloop.counter }}"
			value="{{comment.id}}" />

	<label for="comment{{ forloop.counter }}">{{comment.comment_text}}</label>
<br/>
	{% endfor %}

	<input type="submit" name="Vote"/>

</form>

{% endblock %}

madefood/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MadeFood | Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    
    {% block custom_css %} {% endblock %}
</head>
<body>
    {% include 'includes/navbar.html' %}

    {% block content %}

    {% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

madefood/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_style.css' %}">
{% endblock %}
{% block content %}
<!-- {{ block.super }} -->

<div class="container">
    <div class="row">
        <div class="col">
            <div id="home-content"></div>
            <h1>Made Food - Get Started</h1>
            <h3>Have trouble with prepere food? You have no idea what cook ? Click
            below to spice up your diet</h3>
            <hr>
            <button type="button" class="btn btn-light btn-lg">Get Started</button>
        </div>
    </div>
</div>
<!--<h1>Welcome to MadeFood</h1>-->
<!--<button type="button" class="btn btn-success">Rob cos</button>-->
{% endblock %}

madefood/templates/includes/navbar.html
<nav class="navbar navbar-light" style="background-color: #00b300;">
      <a class="navbar-brand" href="#">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'makefood:recipes' %}">Receipes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shooping List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">About Us</a>
          </li>
        </ul>
      </div>
    </nav>