polls/urls.py
from django.urls import path

from . import views

app_name = "makefood"

urlpatterns = [
    path('recipes/',views.polls_list,name="recipes"),
    path('add/',views.add_recipe,name='add'),
    path('edit/<int:recipes_id>/',views.edit_recipe,name='edit_recipe'),
    
    path('edit/<int:recipes_id>/comment/add/',views.add_comment,name='add_comment'),
	path('delete/comment/<int:comment_id>/', views.delete_comment, name='comment_confirm_delete'),
	path('delete/recipes/<int:recipes_id>',views.delete_recipe,name="recipe_confirm_delete"),
    path('edit/comment/<int:comment_id>/',views.edit_comment,name='edit_comment'),
	path('detail/<int:recipes_id>/',views.recipes_detail,name='detail'),
	path('detail/<int:recipes_id>/vote/',views.recipes_vote,name='vote')
]

polls/templates/polls/add_comment.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<h1 class='text-center'> 
		{% if edit_mode %}
		Edit The Comment using the form below
		{% else %}
		Add New Rating
		{% endif %}
		Using The Form Below
</h1>
		<div class="row">
			<div class="col-sm-6 offset-sm-3">
				<form action="" method="post">
					{% csrf_token %}
					{% for field in form %}
						<div class="form-group">
							{{ field.errors }}
			    			{{ field.label_tag }}
			    			{{ field }}
			  				</div>
					{% endfor %}
					<input type="submit" class="btn btn-primary" value="Sumbit">
					{% if edit_mode %}
          				<a href="{% url 'makefood:comment_confirm_delete' comment.id %}"
              				class='btn btn-danger'>
              			<i class="far fa-trash-alt"></i> Delete
          				</a>
        			{% endif %}
				</form>
			</div>
		</div>
</div>
{% endblock %}

polls/templates/polls/add_recipe.html
{% extends 'base.html' %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_style.css' %}">
{% endblock %}
{% block content %}

<div class="container">
	<h1 class='text-center'> Add Your Recipe</h1>
		<div class="row">
			<div class="col-sm-6 offset-sm-3">
				<form action="" method="post">
					{% csrf_token %}
					{% for field in form %}
						<div class="form-group">
							{{ field.errors }}
			    			{{ field.label_tag }}
			    			{{ field }}
			  				</div>
					{% endfor %}
					<input type="submit" name="submit" class="btn btn-primary" value="Add">
				</form>
			</div>
		</div>
</div>

{% endblock %}

polls/templates/polls/delete_comment_confirm.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-sm-6 offset-sm-3 text-center">

			<form action="" method="post">
			  {% csrf_token %}
			  <input type='submit' class='btn btn-danger' value='I hope you know what you what you are doing!'>
			</form>
		</div>
	</div>
</div>

{% endblock %}

polls/templates/polls/delete_recipe_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-6 offset-sm-3 text-center">
			<form action="" method="post">
  			{% csrf_token %}
  			<input type='submit' class='btn btn-danger' value='Do you want to delete this recipe?'>
			</form>
		</div>
	</div>
</div>


{% endblock %}

polls/templates/polls/edit_recipe.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<h1 class='text-center'> Edit Your Recipe</h1>
		<div class="row">
			<div class="col-sm-6 offset-sm-3">
				<form action="" method="post">
					{% csrf_token %}
					{% for field in form %}
						<div class="form-group">
							{{ field.errors }}
			    			{{ field.label_tag }}
			    			{{ field }}
			  				</div>
					{% endfor %}
					<input type="submit" name="submit" class="btn btn-primary" value="Edit">
					<a  href="{% url 'makefood:add_comment' recipes.id %}" class="btn btn-warning">Add Rating</a>
					<a href="{% url 'makefood:recipe_confirm_delete' recipes.id %}"
              				class='btn btn-danger'>
              			<i class="far fa-trash-alt"></i> Delete
          				</a>
				</form>
				<h3 class='text-center'>Ratings</h3>
				{% for comment in recipes.comment_set.all  %}
				<p><a href="{% url 'makefood:edit_comment' comment.id %}"><i class="far fa-edit"></i></a>{{comment.comment_text}}</p>
				{% endfor %}
			</div>
		</div>
</div>
{% endblock %}

polls/templates/polls/recipes.html
{% extends 'base.html' %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/recipes_style.css' %}">
    {% endblock %}


{% block content %}
<div class="container">
	{% if request.user.is_authenticated %}
		<h2 class='text-center'>Welcome {{ request.user.first_name }} {{ request.user.last_name }}</h2>
	{% else %}
		<h2>You're not logged in . Please sign up and take adventages. It doesn't cost .</h2>
	{% endif %}
    <h1 class='text-center'> Recipes list wchich we prepera for you</h1>
    <div class="row">
    	<div class="col-sm-8 offset-sm-2">
    		{% if messages %}
				<ul class="messages">
					{% for message in messages %}
					<!-- <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li> -->
					<div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
  						{{ message }}
  						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
   						<span aria-hidden="true">&times;</span>
  						</button>
					</div>
					{% endfor %}
				</ul>
			{% endif %}
			<a href="?text=True" class ="btn btn-{% if 'text' in request.GET %}warning{% else %}primary{% endif %}" style="margin-bottom: 10px">Title</a>
			<a href="?pub_date=True" class ="btn btn-{% if 'pub_date' in request.GET %}warning{% else %}primary{% endif %}" style="margin-bottom: 10px">Publish date</a>
			<a href="?num_votes=True" class ="btn btn-{% if 'num_votes' in request.GET %}warning{% else %}primary{% endif %}" style="margin-bottom: 10px">Number of votes</a>
    		<a href="{% url 'makefood:add' %}" class ="btn btn-primary" style="margin-bottom: 10px">Add<i class="fas fa-plus"></i></a>

    		 <form class="form-inline my-2 my-lg-1">
      			<input 
      			class="form-control mr-sm-2" 
      			type="search" 
      			placeholder="Search" 
      			aria-label="Search"
      			name="search" 
      			value="{{search_term}}" 
      			>
      			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    		</form>

    		<ul class="list-group">
		    		{% for recipe in recipes %}
			    	<li
			    	class="list-group-item">
			    	<a href="{% url 'makefood:detail' recipe.id %}"> {{ recipe }}</a>
			    	{% if request.user == recipe.owner %}
			    	<a href="{% url 'makefood:edit_recipe' recipe.id %}" class='float-right'><i class="far fa-edit"></i></a>
			    	{% endif %}
			    	</li>
		    		{% endfor %}
			</ul>

				<div class="pagination">
				    <span class="step-links">
				        {% if recipes.has_previous %}
				            <a href="?page=1&{{params}}">&laquo; first</a>
				            <a href="?page={{ recipes.previous_page_number }}&{{params}}">previous</a>
				        {% endif %}

				        <span class="current">
				            Page {{ recipes.number }} of {{ recipes.paginator.num_pages }}.
				        </span>

				        {% if recipes.has_next %}
				            <a href="?page={{ recipes.next_page_number }}&{{params}}">next</a>
				            <a href="?page={{ recipes.paginator.num_pages }}&{{params}}">last &raquo;</a>
				        {% endif %}
				    </span>
				</div>

    	</div> 
	</div>
</div>
{% endblock %}

<!-- polls = makefood -->
<!-- poll = recipe -->

polls/templates/polls/recipes_detail.html
{% extends 'base.html' %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/recipe_style.css' %}">
{% endblock %}
{% block content %}
<div class="container">
{% if messages %}
				<ul class="messages">
					{% for message in messages %}
					<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			{% endif %}


<p>{{recipes}} - {{recipes.num_votes}} votes</p>
<form action="{% url 'makefood:vote' recipes.id %}" method="post">
	{% csrf_token %}

	{% for comment in recipes.comment_set.all %}

	<input  type="radio" 
			name="comment"
			id = "comment{{ forloop.counter }}"
			value="{{comment.id}}" />

	<label for="comment{{ forloop.counter }}">{{comment.comment_text}} - {{comment.num_votes}}</label>
<br/>
	{% endfor %}
	<input class='btn btn-primary mb-5 mt-2' type="submit" name="Vote" value="Vote" {% if not user_can_vote %}disabled{% endif %}/>
	{% if not user_can_vote %}
		{% for comment_dict in results %}
		<div class="row">
		<div class="col-sm-8">
			{{comment_dict.text}}
				<div class="progress mb-1">
				  <div class="progress-bar progress-bar-striped progress-bar-animated" 
				  		role="progressbar" 
				  		aria-valuenow="75" 
				  		aria-valuemin="0" 
				  		aria-valuemax="100" 
				  		style="width: {{comment_dict.percentage}}%">{{comment_dict.num_votes}}</div>
				</div>
		</div>
		</div>
	{% endfor %}
	{% else %}
	<p>Vote to see results </p>
	{% endif %}
</form>
</div>
{% endblock %}