aboutus/urls.py
from django.urls import path

from . import views

app_name = "aboutus"

urlpatterns = [
    path('aboutus/',views.aboutus,name="aboutus"),
]

accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/',views.login_user,name="login"),
    path('logout/',views.logout_user,name='logout'),
    path('register/',views.user_registration,name="register")
]

madefood/madefood/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('makefood/',include('polls.urls',namespace ='makefood'))
]

madefood/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('makefood/',include('polls.urls',namespace ='makefood')),
    path('accounts/',include('accounts.urls',namespace ='accounts')),
    # path('accounts/',include('django.contrib.auth.urls')),
    path('aboutus/',include('aboutus.urls',namespace ='aboutus')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "makefood"

urlpatterns = [
    path('recipes/',views.polls_list,name="recipes"),
    path('add/',views.add_recipe,name='add'),
    path('edit/<int:recipes_id>/',views.edit_recipe,name='edit_recipe'),
    
    path('edit/<int:recipes_id>/comment/add/',views.add_comment,name='add_comment'),
	path('delete/comment/<int:comment_id>/', views.delete_comment, name='comment_confirm_delete'),
	path('delete/recipes/<int:recipes_id>',views.delete_recipe,name="recipe_confirm_delete"),
    path('edit/comment/<int:comment_id>/',views.edit_comment,name='edit_comment'),
	path('detail/<int:recipes_id>/',views.recipes_detail,name='detail'),
	path('detail/<int:recipes_id>/vote/',views.recipes_vote,name='vote')
]

templates/includes/navbar.html
<nav class="navbar navbar-dark" style="background-color: #00b300; " >
      <a class="navbar-brand" href="#">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <div class="navbar-nav">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>

            <a class="nav-link" href="{% url 'makefood:recipes' %}">Receipes</a>
          
            <a class="nav-link" href="#">Shooping List</a>
          
            <a class="nav-link" href="{% url 'aboutus:aboutus' %}">About Us</a>
       </div>
       <div class="navbar-nav ml auto">
        {% if request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          {% else %}
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        {% endif %}
      </div>

      </div>
    </nav>