aboutus/urls.py
from django.urls import path

from . import views

app_name = "aboutus"

urlpatterns = [
    path('aboutus/',views.aboutus,name="aboutus"),
]

accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/',views.login_user,name="login"),
    path('logout/',views.logout_user,name='logout'),
    path('register/',views.user_registration,name="register")
]

madefood/madefood/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('makefood/',include('polls.urls',namespace ='makefood'))
]

madefood/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('makefood/',include('polls.urls',namespace ='makefood')),
    path('accounts/',include('accounts.urls',namespace ='accounts')),
    # path('accounts/',include('django.contrib.auth.urls')),
    path('aboutus/',include('aboutus.urls',namespace ='aboutus')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "makefood"

urlpatterns = [
    path('recipes/',views.polls_list,name="recipes"),
    path('add/',views.add_recipe,name='add'),
    path('edit/<int:recipes_id>/',views.edit_recipe,name='edit_recipe'),
    
    path('edit/<int:recipes_id>/comment/add/',views.add_comment,name='add_comment'),
	path('delete/comment/<int:comment_id>/', views.delete_comment, name='comment_confirm_delete'),
	path('delete/recipes/<int:recipes_id>',views.delete_recipe,name="recipe_confirm_delete"),
    path('edit/comment/<int:comment_id>/',views.edit_comment,name='edit_comment'),
	path('detail/<int:recipes_id>/',views.recipes_detail,name='detail'),
	path('detail/<int:recipes_id>/vote/',views.recipes_vote,name='vote')
]

aboutus/models.py
from django.db import models

# Create your models here.

aboutus/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime
# Create your views here.
def aboutus(request):
	return render(request,'AboutUs.html',{})

templates/AboutUs.html
{% extends 'base.html' %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/AboutUs.css' %}">
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col">
            <div id="home-content"></div>
            <h4>Personal details: </h4>
            <h4>Software Enginer  </h4>
            <h1>Kamil Stępniewski</h1>
            <h3>E-mail: kamil.stepniewski@outlook.com</h3>
            <h3>Phone Number : +48 501 809 121 </h3>

            <h4>Design</h4>
            <h1>Patrycja Chmielewska</h1>
            <h3>E-mail: patrycja.chmielewska98@gmail.com</h3>
            <h3>Phone Number : +48 509 484 588 </h3>
            <hr>
            
        </div>
    </div>
</div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MadeFood | Eat With Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    
    {% block custom_css %} {% endblock %}
    {% block extra_head %} {% endblock %}

<script 
defer 
src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" 
integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" 
crossorigin="anonymous"></script>

</head>
<body>
    {% include 'includes/navbar.html' %}

    {% block content %}

    {% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_style.css' %}">
{% endblock %}
{% block content %}
<!-- {{ block.super }} -->

<div class="container">
    <div class="row">
        <div class="col">
            <div id="home-content"></div>
            {% if request.user.is_authenticated %}
                <h1> Hello {{request.user.first_name}}  {{request.user.last_name}}</h1>
            {% endif %}   
            <h1>Made Food </h1>
            <h3>Have trouble with prepere food? You have no idea what cook ? Click
            below to spice up your diet</h3>
            <hr>
            <!-- <button type="button" class="btn btn-light btn-lg">Get Started</button> -->
            {% if request.user.is_authenticated %}
          <a class="btn btn-light btn-lg" href="{% url 'makefood:recipes' %}">Get Started</a>
          {% else %}
        <a class="btn btn-light btn-lg" href="{% url 'accounts:register' %}">Get Started</a>
        {% endif %}
        </div>
    </div>
</div>
<!--<h1>Welcome to MadeFood</h1>-->
<!--<button type="button" class="btn btn-success">Rob cos</button>-->
{% endblock %}